services:
  postgres:
    image: postgres:16-alpine
    container_name: utamed_postgres_test
    environment:
      POSTGRES_DB: utamed_test
      POSTGRES_USER: utamed_user
      POSTGRES_PASSWORD: utamed_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U utamed_user -d utamed_test" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
