DROP SCHEMA IF EXISTS "utamed" CASCADE;

DROP SCHEMA IF EXISTS "utamed.Administrativo" CASCADE;

DROP SCHEMA IF EXISTS "utamed.Agenda" CASCADE;

DROP SCHEMA IF EXISTS "utamed.Curso" CASCADE;

DROP SCHEMA IF EXISTS "utamed.Usuario" CASCADE;