<?php

// AUTOGENERADO por scripts/generate_models.php — NO EDITAR MANUALMENTE.
// Fuente de verdad: scripts/permissions_config.php
//
// Mapa plano: slug_de_permiso => tipos_de_contexto_válidos[]
//
// Resolución:
//   _actions        → ['GLOBAL', _valid_contexts del nodo/ancestro]
//   _parent_actions → ['GLOBAL', _valid_parent_context del nodo]
//   Sin contexto    → ['GLOBAL']
//   Wildcards :*    → contexto propio del nodo
//
// Consumido por: App\Support\PermissionContextConstraints
return [
    'usuarios:*' => ['GLOBAL'],
    'usuarios:ver' => ['GLOBAL'],
    'usuarios:crear' => ['GLOBAL'],
    'usuarios:editar' => ['GLOBAL'],
    'usuarios:deshabilitar' => ['GLOBAL'],
    'usuarios:restablecer_contrasena' => ['GLOBAL'],
    'usuarios/permisos:*' => ['GLOBAL'],
    'usuarios/permisos:ver_contextos_disponibles' => ['GLOBAL'],
    'usuarios/permisos:ver_permisos_totales_asignados' => ['GLOBAL'],
    'usuarios/permisos/roles:*' => ['GLOBAL'],
    'usuarios/permisos/roles:gestionar' => ['GLOBAL'],
    'usuarios/permisos/roles:ver' => ['GLOBAL'],
    'usuarios/permisos/roles:crear' => ['GLOBAL'],
    'usuarios/permisos/roles:editar' => ['GLOBAL'],
    'usuarios/permisos/roles:eliminar' => ['GLOBAL'],
    'usuarios/permisos/individuales:*' => ['GLOBAL'],
    'usuarios/permisos/individuales:gestionar' => ['GLOBAL'],
    'usuarios/permisos/individuales:ver_disponibles' => ['GLOBAL'],
    'usuarios/permisos/individuales:ver_quien_tiene' => ['GLOBAL'],
    'facultades:*' => ['GLOBAL', 'FACULTAD'],
    'facultades:ver' => ['GLOBAL', 'FACULTAD'],
    'facultades:crear' => ['GLOBAL', 'FACULTAD'],
    'facultades:editar' => ['GLOBAL', 'FACULTAD'],
    'facultades:eliminar' => ['GLOBAL', 'FACULTAD'],
    'departamentos:*' => ['GLOBAL', 'DEPARTAMENTO'],
    'departamentos:ver' => ['GLOBAL', 'DEPARTAMENTO'],
    'departamentos:crear' => ['GLOBAL', 'DEPARTAMENTO'],
    'departamentos:editar' => ['GLOBAL', 'DEPARTAMENTO'],
    'departamentos:eliminar' => ['GLOBAL', 'DEPARTAMENTO'],
    'carreras:*' => ['GLOBAL', 'CARRERA'],
    'carreras:ver' => ['GLOBAL', 'CARRERA'],
    'carreras:editar' => ['GLOBAL', 'CARRERA'],
    'carreras:eliminar' => ['GLOBAL', 'CARRERA'],
    'carreras:crear' => ['GLOBAL', 'FACULTAD'],
    'carreras/planes:*' => ['GLOBAL', 'CARRERA'],
    'carreras/planes:editar' => ['GLOBAL', 'CARRERA'],
    'carreras/planes:eliminar' => ['GLOBAL', 'CARRERA'],
    'carreras/planes:asignacion_asignaturas' => ['GLOBAL', 'CARRERA'],
    'carreras/planes:crear' => ['GLOBAL', 'CARRERA'],
    'carreras/planes/ver:*' => ['GLOBAL', 'CARRERA'],
    'carreras/planes/ver:ver_detalles' => ['GLOBAL', 'CARRERA'],
    'carreras/planes/ver:ver_malla' => ['GLOBAL', 'CARRERA'],
    'asignaturas:*' => ['GLOBAL'],
    'asignaturas:ver' => ['GLOBAL'],
    'asignaturas:crear' => ['GLOBAL'],
    'asignaturas:editar' => ['GLOBAL'],
    'asignaturas:eliminar' => ['GLOBAL'],
    'cursos:*' => ['GLOBAL', 'CURSO'],
    'cursos:ver' => ['GLOBAL', 'CURSO'],
    'cursos:editar' => ['GLOBAL', 'CURSO'],
    'cursos:eliminar' => ['GLOBAL', 'CURSO'],
    'cursos:crear' => ['GLOBAL', 'CARRERA'],
    'cursos:crear_plantilla' => ['GLOBAL', 'CARRERA'],
    'cursos/inscripciones:*' => ['GLOBAL', 'CURSO'],
    'cursos/inscripciones:ver' => ['GLOBAL', 'CURSO'],
    'cursos/inscripciones:inscribir_alumnos' => ['GLOBAL', 'CURSO'],
    'cursos/inscripciones:eliminar_inscripciones' => ['GLOBAL', 'CURSO'],
    'cursos/secciones:*' => ['GLOBAL', 'CURSO'],
    'cursos/secciones:ver' => ['GLOBAL', 'CURSO'],
    'cursos/secciones:crear' => ['GLOBAL', 'CURSO'],
    'cursos/secciones:crear_plantilla' => ['GLOBAL', 'CURSO'],
    'cursos/secciones:editar' => ['GLOBAL', 'CURSO'],
    'cursos/secciones:eliminar' => ['GLOBAL', 'CURSO'],
    'cursos/unidades:*' => ['GLOBAL', 'CURSO'],
    'cursos/unidades:ver' => ['GLOBAL', 'CURSO'],
    'cursos/unidades:crear' => ['GLOBAL', 'CURSO'],
    'cursos/unidades:crear_plantilla' => ['GLOBAL', 'CURSO'],
    'cursos/unidades:editar' => ['GLOBAL', 'CURSO'],
    'cursos/unidades:eliminar' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:*' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:ver' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:crear' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:crear_plantilla' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:editar' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:eliminar' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:subir_entregas' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:evaluar' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:dar_feedback' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:enviar_recordatorios' => ['GLOBAL', 'CURSO'],
    'cursos/actividades:descargar_entregas' => ['GLOBAL', 'CURSO'],
    'cursos/actividades/grupos:*' => ['GLOBAL', 'CURSO'],
    'cursos/actividades/grupos:ver' => ['GLOBAL', 'CURSO'],
    'cursos/actividades/grupos:crear' => ['GLOBAL', 'CURSO'],
    'cursos/actividades/grupos:editar' => ['GLOBAL', 'CURSO'],
    'cursos/actividades/grupos:eliminar' => ['GLOBAL', 'CURSO'],
    'cursos/programas:*' => ['GLOBAL', 'CURSO'],
    'cursos/programas:ver' => ['GLOBAL', 'CURSO'],
    'cursos/programas:agregar' => ['GLOBAL', 'CURSO'],
    'cursos/programas:eliminar' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:*' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_1' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_2' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_3' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_4' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_5' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_6' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_7' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_8' => ['GLOBAL', 'CURSO'],
    'cursos/programas/modificar:modulo_9' => ['GLOBAL', 'CURSO'],
    '*' => ['GLOBAL'],
];