<?php

namespace App\Enums;

use \App\Contracts\IContextResultStep;
use \App\Contracts\IContextScopeStep;

use \App\Services\Authorization\ContextQueryBuilder;

/**
 * Tipos de contexto válidos para asignación de permisos y roles.
 *
 * #### MANTENIMIENTO DE ESTE ARCHIVO
 *
 * Este archivo tiene DOS secciones con reglas distintas:
 *
 * ##### SECCIÓN AUTOGENERADA (entre @autogenerated:start / @autogenerated:end):
 *     
 * Guarda la configuración establecida de tipos de contexto y su jerarquía, 
 * que es consumida por el sistema de permisos. Es generada automáticamente por 
 * scripts/generate_models.php a partir de la configuración en 
 * scripts/permissions_config.php y el mapa de jerarquía en 
 * scripts/generated_context_hierarchies.php.
 *
 * ##### SECCIÓN MANUAL (métodos de jerarquía al final del enum):
 * 
 * Incluye métodos de navegación de la jerarquía 
 * (immediateParent, ancestorChain, isAncestorOf, descendantTypes).
 * Se puede editar libremente para agregar lógica de jerarquía, 
 * ya que el generador no la toca.
 *
 * Para regenerar la sección autogenerada: `php scripts/generate_models.php`
 *
 * #### USO
 *
 * ##### Navegar la jerarquía:
 * 
 * ContextType::CARRERA->immediateParent() // → DEPARTAMENTO
 * 
 * ContextType::CARRERA->ancestorChain() // → [DEPARTAMENTO, FACULTAD, GLOBAL]
 *
 * ##### Consultar relaciones:
 * 
 * ContextType::FACULTAD->isAncestorOf(ContextType::CARRERA) // → true
 * 
 * ContextType::FACULTAD->descendantTypes() // → [DEPARTAMENTO, CARRERA, CURSO, ACTIVIDAD]
 *
 * ##### Conversión desde BD:
 * 
 * $contextType = ContextType::from($context->tipoContexto->categoria);
 *
 * @see scripts/permissions_config.php — fuente de los tipos de contexto
 * @see scripts/generated_context_hierarchies.php — fuente del mapa de jerarquía
 * @see \App\Services\Authorization\PermissionContextConstraints
 */
enum ContextType: string
{
    // @autogenerated:start
    // Contexto global — aplica a nivel sistema sin restricción de entidad
    case GLOBAL = 'global';

    // Contexto de tipo 'actividad'
    case ACTIVIDAD = 'actividad';

    // Contexto de carrera — restricción a una carrera específica
    case CARRERA = 'carrera';

    // Contexto de curso — restricción a un curso específico
    case CURSO = 'curso';

    // Contexto de departamento — restricción a un departamento específico
    case DEPARTAMENTO = 'departamento';

    // Contexto de facultad — restricción a una facultad específica
    case FACULTAD = 'facultad';

    // ──────────────────────────────────────────────────────────────────────────
    // MAPA DE JERARQUÍA — regenerado desde scripts/generated_context_hierarchies.php
    // ──────────────────────────────────────────────────────────────────────────

    /**
     * Mapa estático de valor de contexto → tipo padre inmediato (self), o null si es raíz.
     *
     * • Tipos raíz concretos (ej: facultad) apuntan a self::GLOBAL.
     * • El propio GLOBAL apunta a null (raíz absoluta del árbol).
     *
     * Consumido internamente por immediateParent() — no invocar directamente.
     *
     * @return array<string, self|null>
     */
    public static function parentMap(): array
    {
        return [
            'global' => null,
            'carrera' => self::DEPARTAMENTO,
            'departamento' => self::FACULTAD,
            'facultad' => self::GLOBAL,
            'actividad' => self::CURSO,
            'curso' => self::CARRERA,
        ];
    }
    // @autogenerated:end

    // ──────────────────────────────────────────────────────────────────────────
    // MÉTODOS PUROS DE JERARQUÍA — lógica manual / estable
    // ──────────────────────────────────────────────────────────────────────────

    /**
     * Retorna el tipo padre inmediato en la jerarquía, o null si es la raíz absoluta.
     *
     * EJEMPLOS:
     *   Entrada          Salida
     *   ──────────────── ────────────────
     *   CARRERA       →  DEPARTAMENTO
     *   DEPARTAMENTO  →  FACULTAD
     *   FACULTAD      →  GLOBAL
     *   CURSO         →  CARRERA
     *   ACTIVIDAD     →  CURSO
     *   GLOBAL        →  null
     *
     * COMPLEJIDAD: O(1) — lookup directo en parentMap()
     */
    public function immediateParent(): ?self
    {
        return self::parentMap()[$this->value] ?? null;
    }

    /**
     * Retorna la cadena COMPLETA de ancestros desde el padre inmediato hasta GLOBAL (inclusive).
     *
     * Camina iterativamente por immediateParent() hasta alcanzar null.
     * Siempre incluye GLOBAL como último elemento (antes de null).
     *
     * EJEMPLOS:
     *   CARRERA  → [DEPARTAMENTO, FACULTAD, GLOBAL]
     *   CURSO    → [CARRERA, DEPARTAMENTO, FACULTAD, GLOBAL]
     *   FACULTAD → [GLOBAL]
     *   GLOBAL   → []  (sin ancestros)
     *
     * UTILIDAD:
     *   • Resolver permisos que aplican a "cualquier ancestro"
     *   • Expandir contextos para búsquedas transitivas
     *   • Validar relaciones de subcontexto
     *
     * @return self[]
     */
    public function ancestorChain(): array
    {
        $chain = [];
        $current = $this->immediateParent();
        while ($current !== null) {
            $chain[] = $current;
            $current = $current->immediateParent();
        }
        return $chain;
    }

    /**
     * Determina si este tipo es ancestro (directo o transitivo) de $other.
     *
     * NO es reflexivo: CARRERA->isAncestorOf(CARRERA) → false
     *
     * EJEMPLOS:
     *   FACULTAD->isAncestorOf(CARRERA)  → true   (FAC es ancestro de CAR)
     *   GLOBAL->isAncestorOf(CARRERA)    → true   (GLOBAL es ancestro de todo)
     *   CARRERA->isAncestorOf(FACULTAD)  → false  (relación inversa)
     *   CARRERA->isAncestorOf(CARRERA)   → false  (no reflexivo)
     *
     * COMPLEJIDAD: O(h) donde h = altura hasta GLOBAL (≤5 típicamente)
     */
    public function isAncestorOf(self $other): bool
    {
        foreach ($other->ancestorChain() as $t) {
            if ($t === $this) {
                return true;
            }
        }
        return false;
    }

    /**
     * Determina si este tipo es descendiente (directo o transitivo) de $ancestor.
     *
     * Inverso semántico de isAncestorOf(): $a->isDescendantOf($b) ≡ $b->isAncestorOf($a)
     *
     * EJEMPLOS:
     *   CARRERA->isDescendantOf(FACULTAD)  → true
     *   CURSO->isDescendantOf(GLOBAL)      → true
     *   FACULTAD->isDescendantOf(CARRERA)  → false
     */
    public function isDescendantOf(self $ancestor): bool
    {
        return $ancestor->isAncestorOf($this);
    }

    /**
     * Retorna TODOS los tipos que son descendientes (directos o transitivos) de este tipo.
     *
     * EJEMPLOS:
     *   FACULTAD->descendantTypes()  → [DEPARTAMENTO, CARRERA, CURSO, ACTIVIDAD]
     *   CARRERA->descendantTypes()   → [CURSO, ACTIVIDAD]
     *   GLOBAL->descendantTypes()    → [FACULTAD, DEPARTAMENTO, ...] (Todos los demás tipos)
     *   ACTIVIDAD->descendantTypes() → [] (sin subordinados)
     *
     * @return self[]
     */
    public function descendantTypes(): array
    {
        return array_values(array_filter(
            self::cases(),
            $this->isAncestorOf(...),
        ));
    }

    // ──────────────────────────────────────────────────────────────────────────
    // CONSULTAS BD — entry point del builder fluido
    // ──────────────────────────────────────────────────────────────────────────

    /**
     * Inicia una consulta sobre instancias de contexto (usuario.contexto) filtrando
     * por el tipo de contexto que instancia la consulta.
     *
     * Usa el patrón Builder para elegir un alcance antes de acceder a los datos.
     * Esto previene encadenamientos inválidos en tiempo de compilación / IDE.
     *
     * ALCANCES DISPONIBLES (paso 1) (IContextScopeStep):
     * 
     *   ->strict()          — solo instancias de ESTE tipo exacto
     *   ->withDescendants() — este tipo + todos sus subordinados en la jerarquía
     *
     * TERMINALES DISPONIBLES (paso 2, tras elegir alcance) (IContextResultStep):
     * 
     *   ->toIds()     — Retorna array<int> de id_contexto (eficiente para whereIn)
     *   ->toBuilder() — Clona el Eloquent Builder para permitir agregar filtros adicionales
     *   ->count()     — Hace un conteo sin cargar modelos
     *
     * EJEMPLOS:
     * 
     *   // IDs de Contextos de todas las carreras
     *   $ids = ContextType::CARRERA->query()->strict()->toIds();
     *
     *   // Todos los contextos bajo una facultad (departamentos, carreras, cursos, actividades)
     *   $ids = ContextType::FACULTAD->query()->withDescendants()->toIds();
     *
     *   // Builder para filtros adicionales
     *   $builder = ContextType::CURSO->query()->strict()->toBuilder()->where('activo', true);
     *
     * FLUJO INVÁLIDO (error en IDE):
     * 
     *   ContextType::CARRERA->query()->toIds()                     // ❌ falta elegir alcance
     *   ContextType::CARRERA->query()->strict()->withDescendants() // ❌ no se puede re-elegir alcance
     *
     * @see \App\Contracts\IContextScopeStep
     * @see \App\Services\Authorization\ContextQueryBuilder
     */
    public function query(): IContextScopeStep
    {
        // Usa el tipo de contexto actual para usarlo en el builder fluido de selección de alcance.
        $type = $this;

        // Selección de alcance:
        // ->  Retorna un builder configurado para el tipo y alcance elegido.
        return new class ($type) implements IContextScopeStep {
            public function __construct(private readonly ContextType $type)
            {}

            /**
             * @inheritDoc
             */
            public function strict(): IContextResultStep
            {
                return ContextQueryBuilder::strict($this->type);
            }

            /**
             * @inheritDoc
             */
            public function withDescendants(): IContextResultStep
            {
                return ContextQueryBuilder::withDescendants($this->type);
            }
        };
    }
}
